# Generated by Django 4.0.6 on 2022-08-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_meal_delete_mealsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequirements',
            name='description',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
